# Generated by Django 5.0.4 on 2024-05-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0002_rename_reports_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='report',
            new_name='question',
        ),
    ]
