# Generated by Django 5.0.4 on 2024-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0005_response_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
